#!/bin/bash

TARGET_DIR="/usr/local/bin/keeys"

# Kopier programmet til installationsmappen
mkdir -p "$TARGET_DIR"
cp -r "$PWD"/* "$TARGET_DIR"

# Tilføj mappen til PATH, hvis den ikke allerede er der
if ! echo "$PATH" | grep -q "$TARGET_DIR"; then
  echo "export PATH=\$PATH:$TARGET_DIR" >> /etc/paths
fi

exit 0
