name: Build and Package Installers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Package Installers
    runs-on: ubuntu-latest

    steps:
      # Tjek koden ud
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build for Windows
      - name: Build for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained -o ./output/windows

      # Build for macOS
      - name: Build for macOS
        run: dotnet publish -c Release -r osx-x64 --self-contained -o ./output/macos

      # Generate Windows Installer
      - name: Generate Windows Installer
        run: |
          sudo apt-get update
          sudo apt-get install nsis -y
          makensis ./scripts/keeys-installer.nsi

      # Generate macOS Installer
      - name: Generate macOS Installer
        run: |
          chmod +x ./scripts/postinstall
          pkgbuild --root ./output/macos \
                   --scripts ./scripts \
                   --identifier com.keeys.passwordmanager \
                   --version 1.0 \
                   --install-location /usr/local/bin/keeys \
                   ./artifacts/keeys-installer.pkg

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keeys-installers
          path: ./artifacts
